spring:
  data:
    mongodb:
      database: inventory-service
      port: '27017'
      host: localhost
      auto-index-creation: true
  application:
    name: INVENTORY-SERVICE
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'